travis:
  secure:
    BINSTAR_TOKEN: bltGXA0U4RteWk13VCUxhtL+PWzsPn4n9QCvRtlvgY9nska8pT5UMEWBBWl7CN8cfnr+EDPAfP2wWODjzkl8rzU2/jLQdM+4ZVJP1g/ZdnEGVJtJoRBdEtmAgFDe2ZnY6EI/8+96rgEWFKOjUcCccvPfHlDOEUFTa/LnKBf/bpTP6nyKB/FRmf8A03qxSdrXyy0OjGEf8iuVJhOLykGrYnqw/4x/rGOCg59a5o7orgCD3r0lUbntOpIp421Db1Lier+Y/h3qqeDTybvKtML2BlU7RJFdmbJWY/RSeW6KOopgbLR3FRiQEplrrZOS5Nr2wtRc86OlyElrVSIvDbKlbQSDYFsEZX0Aa8enWn6YwEMg0apH1MLUdqVliQTGSb7hJv0aGXLyFC6BpvMQpKcK2/zV9U4mReC06kaGKws1JRZDqFTi+X/PXmJVYF4s9xzgsDXPE89AYuGK6+WNGit7h4XZ77zk8tPo4FjNLe782pmd78HH1WygPoBiKM10G7Iely7TN3KN3GckCOABroWzShxnUvJD7lJ2c7Jh9D829a/TD1qIJRQ5xPGiVE+uLWm8rPsyo4DrLcwpaAqOa0OVUK141UAeN/jP4BevOV+vua8w1tMAHBiyarmYVBwzoJoPHKBoKYKjGtwmJmHqQnYd+7VAWEgcyi1PKt0FjmPzams=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
